### ISSUE TITLE
“OverflowError: Python int too large to convert to C long” on windows but not linux

### ISSUE THREAD

**Issue by rnd-shtar** [CyberZHG/keras-self-attention#10]
attention = SeqSelfAttention(attention_activation='sigmoid',
                                     history_only=True,
                                     attention_type=SeqSelfAttention.ATTENTION_TYPE_ADD
                                     )(biLSTM_LSTM_H)
raises:
OverflowError: Python int too large to convert to C long.
This happens on windows, on Linux there is not problem.
When removing history_only=True parameter it works.

**Comment by CyberZHG** [comment]
The default attention width is too large for 32-bit integers. I've released a new version. Thanks for pointing out.
