### ISSUE TITLE
How to plot an attention heat map ? 

### ISSUE THREAD

**Issue by Bertorob** [CyberZHG/keras-self-attention#11]
I tried the flag return_attention = true but it returns an array filled with ones.

**Comment by cristianmtr** [comment]
I'm also interested in producing a visualization of the attention. Any tips?

**Comment by CyberZHG** [comment]
@Bertorob @cristianmtr 
https://github.com/PoWWoP/UOI-1806.01264/blob/master/demo.py#L212-L218

**Comment by xuzhang5788** [comment]
@CyberZHG 
The link you gave is not accessable now.

**Comment by AmrARaouf** [comment]
Hi @CyberZHG,

Could you please provide an alternative link? I'm very interested in visualizing my weights!

Thank you

**Comment by CyberZHG** [comment]
@AmrARaouf 

I don't know where the repo is gone. But you can find some forked ones:

https://github.com/thirasan/UOI-1806.01264/blob/master/demo.py#L212-L218

**Comment by AmrARaouf** [comment]
Thank you for your prompt reply.

I would like to add, to whom it may interest, that I followed this stackoverflow thread and was able to visualize the attention weights.

https://stackoverflow.com/questions/58356868/how-visualize-attention-lstm-using-keras-self-attention-package
