### ISSUE TITLE
Dense layer after Self Attention Layer throws an error

### ISSUE THREAD

**Issue by TarunTater** [CyberZHG/keras-self-attention#12]
If I try the code given in the example with text data : 

```
import keras
from keras_self_attention import SeqSelfAttention

model = keras.models.Sequential()
model.add(keras.layers.Embedding(input_dim=10000,
                                 output_dim=300,
                                 mask_zero=True))
model.add(keras.layers.Bidirectional(keras.layers.LSTM(units=128,
                                                       return_sequences=True)))
model.add(SeqSelfAttention(attention_activation='sigmoid'))
model.add(keras.layers.Dense(units=5))
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['categorical_accuracy'],
)
model.summary()
```

It throws an error : 

> ValueError: Error when checking target: expected dense_10 to have 3 dimensions, but got array with shape (28696, 2)

I need to add another lstm layer after selfattention with return_sequence=False, to make this run. Am i missing something? The output from self attention layer is of shape (maxlen, number of units in lstm layer(say units=200)), how do we get a vector out of the layer of size (units=200)?

**Comment by CyberZHG** [comment]
Same as #9. The output of the attention layer in this repo has the same shape as the input (therefore it is 3 dimensional in this case). What you need maybe something like this one: [SeqWeightedAttention](https://github.com/CyberZHG/keras-self-attention/blob/master/keras_self_attention/seq_weighted_attention.py).
