### ISSUE TITLE
Scaled Dot Product attention error

### ISSUE THREAD

**Issue by AliOsm** [CyberZHG/keras-self-attention#14]
When applying scaled dot product attention is gives the following error:

```
TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.
```

Any idea?

**Comment by CyberZHG** [comment]
A list of three tensors is needed as input. I've made an update and single input is supported now.

**Comment by AliOsm** [comment]
It is works now, but unfortunately, either ScaledDotProduct, SeqSelfAttention or SeqWeightedAttention did not make any improvement in text classification or sequence labeling tasks, any idea?
