### ISSUE TITLE
can this be used in a seq 2 seq task?

### ISSUE THREAD

**Issue by cristianmtr** [CyberZHG/keras-self-attention#15]
Can this be used in a seq 2 seq task? With an encoder LSTM and a decoder LSTM? The examples don't seem to cover this

**Comment by AliOsm** [comment]
If you are using TensorFlow you can use AttentionWrapper instead of this library, it is built-in functionality and supports Bahdanau and Luong attention.
https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/AttentionWrapper
