### ISSUE TITLE
results[2]应该改为results[0]

### ISSUE THREAD

**Issue by xiayangdi** [CyberZHG/keras-self-attention#26]
https://github.com/CyberZHG/keras-self-attention/blob/2d4f5e67ffcbccf0a7bb5d22faec266253e9fd7e/tests/scaled_dot_attention/test_history.py#L43

感觉results[2]应该改为results[0]吧？不过自己是新手，不太确定自己对不对，给大神反馈下

**Comment by CyberZHG** [comment]
对，这里是不相等的时候的输出，因为没触发过忽略了。

**Comment by CyberZHG** [comment]
已经改完发布。
