### ISSUE TITLE
初始化器写成了正则化器

### ISSUE THREAD

**Issue by xiayangdi** [CyberZHG/keras-self-attention#27]
https://github.com/CyberZHG/keras-self-attention/blob/2d4f5e67ffcbccf0a7bb5d22faec266253e9fd7e/keras_self_attention/seq_self_attention.py#L88-L89

两个 keras.regularizers.serialize，应该是  keras.initializers.serialize

**Comment by CyberZHG** [comment]
🙀 还好初始化后一般立刻训练……你要想改的话可以直接编辑文件提个PR。

**Comment by CyberZHG** [comment]
已经改完发布。
