### ISSUE TITLE
在加法模式和乘法模式里，一个加 ba,一个加ba[0]

### ISSUE THREAD

**Issue by xiayangdi** [CyberZHG/keras-self-attention#28]
https://github.com/CyberZHG/keras-self-attention/blob/2d4f5e67ffcbccf0a7bb5d22faec266253e9fd7e/keras_self_attention/seq_self_attention.py#L215

ba的shape为(1,)，在加法模式中是直接加 self.ba，在乘法模式里却是加 self.ba[0]，感觉应该没必要取[0]

**Comment by CyberZHG** [comment]
这个跟兼容theano有关，去掉会报错。
