### ISSUE TITLE
SeqSelfAttention returning tuple (tensor, weights) raise TypeError on Tensor object not iterable

### ISSUE THREAD

**Issue by McKracken** [CyberZHG/keras-self-attention#3]
Hi,

I'm running the code Regularizer example from your README, and I getting the following error from SeqSelAttention layer

`TypeError: Tensor objects are not iterable when eager execution is not enabled. To iterate over this tensor use tf.map_fn. `

raised in "lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 436, in __iter__

I'm using:
- python 3.6.5 
- tensorflow 1.9.0

Any clue?

**Comment by McKracken** [comment]
Thanks, now it works. 
Is there a way to access the attention weights/values anyway? In case you'd like to use them for visualization or other purposes?

**Comment by CyberZHG** [comment]
```python
att_layer, att_weights = SeqSelfAttention(..., return_attention=True, ...)
```

**Comment by McKracken** [comment]
Ok! That's great. I'm gonna do some hard core tests in a while.
Can I just ask a last thing (I promise I'll close the thread afterwards): do you have a precise paper or other reference to the attention equations reported in the README? I found many other papers and videos, but they all have similar equations (and thus structures), but not the one with exactly that ones. For example, in one of the most famous there's the tanh operator used on the context C (which in you case should correspond to x, I suppose) and the inputs y_i (corresponding to your x_t), but there's no activation function afterwards. So, I was just guessing whether you can point out some references for those equations. Thanks!

**Comment by CyberZHG** [comment]
The most similar one: https://arxiv.org/pdf/1806.01264.pdf

**Comment by McKracken** [comment]
Right, I see, thank you. 
When you use the `attention_width` parameter, does it related to the width in terms of previous and following inputs consider for the actual token. That meaning, that if we're evaluating the attention for the input x_t with an attention_width of 3, the inputs x_t-3, x_t-2, x_t-1 and x_t+3, x_t+2, x_t+1 will be considered in the evaluation?

**Comment by CyberZHG** [comment]
If `attention_width=3`, then x_{t-1}, x_t, x_{t+1} will be used.
