### ISSUE TITLE
Tensorflow 2.0 Compatibility

### ISSUE THREAD

**Issue by SamanehSaadat** [CyberZHG/keras-self-attention#31]
Hi,

When I tried to use this package in Tensorflow 2.0, I got the following error:

> RuntimeError: It looks like you are trying to use a version of multi-backend Keras that does not support TensorFlow 2.0. We recommend using `tf.keras`, or alternatively, downgrading to TensorFlow 1.14.

**Comment by mohamedScikitLearn** [comment]
@CyberZHG  This issue is still open, any suggestions ?
