### ISSUE TITLE
Does it support functional API?

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [CyberZHG/keras-self-attention#5]
Could you please provide real-world examples of the models with combination of keras functional API?

**Comment by ErmiaAzarkhalili** [comment]
It's it true for keras_multihead?!

**Comment by CyberZHG** [comment]
> It's it true for keras_multihead?!

I'm not sure what you're expecting. [Multi-head attention](https://github.com/CyberZHG/keras-multi-head#multi-head-attention) would be easier to use if you need it.
