### ISSUE TITLE
module 'keras' has no attribute 'applications'

### ISSUE THREAD

**Issue by zlindaz2411** [CyberZHG/keras-self-attention#56]
I copy pasted the example 

```
import keras
from keras_self_attention import SeqSelfAttention


model = keras.models.Sequential()
model.add(keras.layers.Embedding(input_dim=10000,
                                 output_dim=300,
                                 mask_zero=True))
model.add(keras.layers.Bidirectional(keras.layers.LSTM(units=128,
                                                       return_sequences=True)))
model.add(SeqSelfAttention(attention_activation='sigmoid'))
model.add(keras.layers.Dense(units=5))
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['categorical_accuracy'],
)
model.summary()
```
and i get the error "module 'keras' has no attribute 'applications'". I am using Google Colab and the latest version of tensorflow and keras. Do you know why is this happening? thank you in advance.

**Comment by raspatiocan** [comment]
i have the same problem.
you need to downgrade Tensorflow 2.5.0 to 2.4.0 and python 3.7.10 to 3.6.9
i think that will solve the problem.
but i dont know how to downgrade python version in colab.
if you have a solution for downgrade python version in colab, please share here.

**Comment by aspil** [comment]
I had this problem in both Colab and local projects when I used SeqSelfAttention.
For my case, I imported every package I got an error for, until no more AttributeErrors occurred. Try this:
```
from keras import applications, datasets, preprocessing, wrappers
from keras_self_attention import SeqSelfAttention
````

I guess you can try the same, it's easier to do than downgrading versions, but this is more of a workaround than an actual solution..
Also I downloaded the package locally and tried to explicitly import the packages required inside **backend.py** and that did the job as well.

**Comment by zlindaz2411** [comment]
> I had this problem in both Colab and local projects when I used SeqSelfAttention.
> For my case, I imported every package I got an error for, until no more AttributeErrors occurred. Try this:
> 
> ```
> from keras import applications, datasets, preprocessing, wrappers
> from keras_self_attention import SeqSelfAttention
> ```
> 
> I guess you can try the same, it's easier to do than downgrading versions, but this is more of a workaround than an actual solution..
> Also I downloaded the package locally and tried to explicitly import the packages required inside **backend.py** and that did the job as well.

Thank you! This solved the problem!
