### ISSUE TITLE
Error with flatten

### ISSUE THREAD

**Issue by sandeepbhutani304** [CyberZHG/keras-self-attention#58]
[https://datascience.stackexchange.com/questions/96660/how-to-use-flatten-with-seqselfattention](https://datascience.stackexchange.com/questions/96660/how-to-use-flatten-with-seqselfattention)  

I want to use SeqSelfAttention , but in final layer the dimension need to be reduced. However, adding Flatten gives following error : `ValueError: The last dimension of the inputs to Dense should be defined. Found None.`

Model summary:

```
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
embedding (Embedding)        (None, 200, 300)          5379900   
_________________________________________________________________
bidirectional_2 (Bidirection (None, 200, 40)           51360     
_________________________________________________________________
seq_self_attention_1 (SeqSel (None, None, 40)          2625      
_________________________________________________________________
dropout_3 (Dropout)          (None, None, 40)          0         
_________________________________________________________________
dense_5 (Dense)              (None, None, 5)           205       
_________________________________________________________________
dense_6 (Dense)              (None, None, 1)           6         
=================================================================
Total params: 5,434,096
Trainable params: 54,196
Non-trainable params: 5,379,900
```
______________________________________________________________
Need to add Flatten between dense_5 and dense_6 .

**Comment by sandeepbhutani304** [comment]
No one to answer?

**Comment by vaskozl** [comment]
@sandeepbhutani304 I hit the same error today on TF 2.5. Though for me the model summary is slightly different `module_wrapper_1` instead of `seq_self_attention_1`.

Seems to be related to `tf.keras` vs `keras`and the layer not being detected properly and thus tensorflow attempting to wrap it with a module_wrapper.

I was able to solve my issue by wrapping the layer in a basic `Layer()`.

```
model.add(Layer(SeqSelfAttention(attention_activation='relu'), name="attention"))
```

**Comment by sandeepbhutani304** [comment]
> @sandeepbhutani304 I hit the same error today on TF 2.5. Though for me the model summary is slightly different `module_wrapper_1` instead of `seq_self_attention_1`.
> 
> Seems to be related to `tf.keras` vs `keras`and the layer not being detected properly and thus tensorflow attempting to wrap it with a module_wrapper.
> 
> I was able to solve my issue by wrapping the layer in a basic `Layer()`.
> 
> ```
> model.add(Layer(SeqSelfAttention(attention_activation='relu'), name="attention"))
> ```

Thanks... By wrapping in layer the error was gone... although accuracy has gone down drastically.. let me check and revert

**Comment by filefolder** [comment]
I'm having the same issue... not my code but it was written pre tf 2.0 and now won't work with 2.5, even after the typical adjustments. Tried to wrap it with a Layer but it says it was already a Layer. Sorry I'm not much help here but there's definitely something awry.
