### ISSUE TITLE
attention w/ TimeDistributed

### ISSUE THREAD

**Issue by phiweger** [CyberZHG/keras-self-attention#6]
Hi,

Is it possible to use the attention layer w/ a `TimeDistributed(Dense(...))`?

If so, how would one have to modify the example in the README?

Thank you,
Adrian

**Comment by CyberZHG** [comment]
Generally, `TimeDistributed` just reshape the inputs to one batch with bigger batch size (more specifically, reshaped batch size = batch size x time length). You could be able to change `Dense` to any other layers.

**Comment by phiweger** [comment]
sorry I am very new to keras -- how would I implement this in code?

thanks a lot!
