### ISSUE TITLE
Issue with importing SeqSelfAttention

### ISSUE THREAD

**Issue by katekats** [CyberZHG/keras-self-attention#61]
Hello,

I have an issue when I try to import SeqSelfAttention, I get the message:ImportError: cannot import name ‘get_config’.

Any idea how to solve this would be welcomed.

**Comment by matheus695p** [comment]
same here !!

**Comment by mkuehn94** [comment]
in backend.py try to replace line:
`import keras`
with
`from tensorflow import keras`

**Comment by liellnima** [comment]
> in backend.py try to replace line: `import keras` with `from tensorflow import keras`

This solved the issue for me! Thank you very much!
(I had the following error: AttributeError: module 'keras' has no attribute 'applications')
