### ISSUE TITLE
It is ready to work with multivariate  ?

### ISSUE THREAD

**Issue by rjpg** [CyberZHG/keras-self-attention#8]
hello,

I have this model : 
```
        variables=9
        timeSteps=128 
        inputNet = Input(shape=(timeSteps,variables)) 
               lstm=Bidirectional(LSTM(100,recurrent_dropout=0.4,dropout=0.4,return_sequences=True),merge_mode='concat')(inputNet) #worse using stateful=True
        lstm=SeqSelfAttention(attention_activation='sigmoid')(lstm)  
      lstm=Bidirectional(LSTM(50,recurrent_dropout=0.4,dropout=0.4,return_sequences=False),merge_mode='concat')(lstm) #worse using stateful=True         
        classificationLayer=Dense(classes,activation='softmax')(lstm)
        model=Model(inputNet,classificationLayer)
```

It do not seam to improve to the same model but without the line :
` lstm=SeqSelfAttention(attention_activation='sigmoid')(lstm)    `   

My code makes sense or my problem/data does not need attention? 

Thanks !

**Comment by CyberZHG** [comment]
Attention layers have many definitions and implementations. This implementation is more suitable for seq2seq tasks. Maybe this is not what you want (and it is not guaranteed to have a better result with attention).

**Comment by rjpg** [comment]
Ok, thanks!    I am thinking about using seq2seq for a GAN (give half of the time series - and the type strong up, week up, null, week down , strong down - and generate the other half in the generator part...  ) and this project will probably be used ;-)
