### ISSUE TITLE
Output of the layer is 3 Dimension and not 2 Dimension

### ISSUE THREAD

**Issue by hardikmeisheri** [CyberZHG/keras-self-attention#9]
Compute_out_shape outputs shape = (?, max seqeunce length, units of bidirectional layer)

**Comment by CyberZHG** [comment]
That's it.

**Comment by hardikmeisheri** [comment]
Correct if I am wrong but shouldn't the output of the attention layer should be 2-D (?, units of bidirectional layer)? 
Or are we passing the 3-D input to Dense Layers?

**Comment by CyberZHG** [comment]
It depends. This is usually used for seq2seq tasks.
